"""add_tab2_and_tab3_columns

Revision ID: 72f0919c0006
Revises: 3c51c5cef1ba
Create Date: 2026-04-29 23:49:07.984821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72f0919c0006'
down_revision: Union[str, Sequence[str], None] = '3c51c5cef1ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecast_cache', sa.Column('confidence_tier', sa.String(length=20), nullable=True))
    op.add_column('model_diagnostics', sa.Column('validation_graph_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_diagnostics', 'validation_graph_json')
    op.drop_column('forecast_cache', 'confidence_tier')
    # ### end Alembic commands ###
