"""initial master schema

Revision ID: 7e2b14097928
Revises: 
Create Date: 2026-04-26 23:00:29.464824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e2b14097928'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sarimax_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('model_path', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('pipeline_ver', sa.String(length=20), nullable=True),
    sa.Column('p', sa.Integer(), nullable=True),
    sa.Column('d', sa.Integer(), nullable=True),
    sa.Column('q', sa.Integer(), nullable=True),
    sa.Column('seasonal_p', sa.Integer(), nullable=True),
    sa.Column('seasonal_d', sa.Integer(), nullable=True),
    sa.Column('seasonal_q', sa.Integer(), nullable=True),
    sa.Column('exog_features_json', sa.JSON(), nullable=True),
    sa.Column('aic_score', sa.Float(), nullable=True),
    sa.Column('bic_score', sa.Float(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('mape', sa.Float(), nullable=True),
    sa.Column('wmape', sa.Float(), nullable=True),
    sa.Column('train_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('train_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_data_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('booking_value', sa.Float(), nullable=True),
    sa.Column('is_holiday', sa.Boolean(), nullable=True),
    sa.Column('weather_indicator', sa.Float(), nullable=True),
    sa.Column('additional_exog_json', sa.JSON(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_data_log_record_date'), 'training_data_log', ['record_date'], unique=False)
    op.create_table('forecast_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('forecast_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('predicted', sa.Float(), nullable=True),
    sa.Column('lower_bound', sa.Float(), nullable=True),
    sa.Column('upper_bound', sa.Float(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('periods_ahead', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['sarimax_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecast_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('data_quality_pct', sa.Float(), nullable=True),
    sa.Column('revenue_total', sa.Float(), nullable=True),
    sa.Column('growth_rate', sa.Float(), nullable=True),
    sa.Column('expected_bookings', sa.Integer(), nullable=True),
    sa.Column('peak_travel_period', sa.String(length=100), nullable=True),
    sa.Column('yearly_bookings_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['sarimax_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_diagnostics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('residuals_json', sa.JSON(), nullable=True),
    sa.Column('acf_values_json', sa.JSON(), nullable=True),
    sa.Column('pacf_values_json', sa.JSON(), nullable=True),
    sa.Column('adf_stat', sa.Float(), nullable=True),
    sa.Column('adf_pvalue', sa.Float(), nullable=True),
    sa.Column('adf_conclusion', sa.String(length=100), nullable=True),
    sa.Column('ljungbox_stat', sa.Float(), nullable=True),
    sa.Column('ljungbox_pvalue', sa.Float(), nullable=True),
    sa.Column('ljungbox_conclusion', sa.String(length=100), nullable=True),
    sa.Column('jarquebera_stat', sa.Float(), nullable=True),
    sa.Column('jarquebera_pvalue', sa.Float(), nullable=True),
    sa.Column('jarquebera_conclusion', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['sarimax_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_diagnostics')
    op.drop_table('forecast_snapshots')
    op.drop_table('forecast_cache')
    op.drop_index(op.f('ix_training_data_log_record_date'), table_name='training_data_log')
    op.drop_table('training_data_log')
    op.drop_table('sarimax_models')
    # ### end Alembic commands ###
