"""add confidence_tier sigma2 validation_graph_json

Revision ID: 8307f3ecb416
Revises: be8c1e78b5f9
Create Date: 2026-05-02 00:40:36.995919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8307f3ecb416'
down_revision: Union[str, Sequence[str], None] = 'be8c1e78b5f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
