"""add json columns

Revision ID: 9072673648ba
Revises: d67243dfb197
Create Date: 2026-04-26 22:35:47.468473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9072673648ba'
down_revision: Union[str, Sequence[str], None] = 'd67243dfb197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('forecast_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('predicted', sa.Float(), nullable=True),
    sa.Column('lower_bound', sa.Float(), nullable=True),
    sa.Column('upper_bound', sa.Float(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('periods_ahead', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['sarimax_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecast_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('data_quality_pct', sa.Float(), nullable=True),
    sa.Column('revenue_total', sa.Float(), nullable=True),
    sa.Column('growth_rate', sa.Float(), nullable=True),
    sa.Column('expected_bookings', sa.Integer(), nullable=True),
    sa.Column('peak_travel_period', sa.String(length=100), nullable=True),
    sa.Column('yearly_bookings_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['sarimax_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_training_jobs_status'), table_name='training_jobs')
    op.drop_table('training_jobs')
    op.drop_index(op.f('ix_raw_bookings_batch_id'), table_name='raw_bookings')
    op.drop_index(op.f('ix_raw_bookings_generation_date'), table_name='raw_bookings')
    op.drop_index(op.f('ix_raw_bookings_order_reference'), table_name='raw_bookings')
    op.drop_index(op.f('ix_raw_bookings_origin_destination'), table_name='raw_bookings')
    op.drop_index(op.f('ix_raw_bookings_travel_date'), table_name='raw_bookings')
    op.drop_table('raw_bookings')
    op.drop_table('dashboard_kpi_cache')
    op.drop_index(op.f('ix_ingestion_batches_file_hash_sha256'), table_name='ingestion_batches')
    op.drop_index(op.f('ix_ingestion_batches_hash'), table_name='ingestion_batches')
    op.drop_index(op.f('ix_ingestion_batches_uploaded_at'), table_name='ingestion_batches')
    op.drop_table('ingestion_batches')
    op.drop_index(op.f('ix_forecasts_forecast_week'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_model_id'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_model_diagnostics_model_id'), table_name='model_diagnostics')
    op.drop_constraint(op.f('model_diagnostics_model_id_fkey'), 'model_diagnostics', type_='foreignkey')
    op.create_foreign_key(None, 'model_diagnostics', 'sarimax_models', ['model_id'], ['id'])
    op.add_column('sarimax_models', sa.Column('model_path', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_sarimax_models_is_active'), table_name='sarimax_models')
    op.drop_column('sarimax_models', 'model_size_bytes')
    op.drop_column('sarimax_models', 'model_blob')
    op.drop_column('sarimax_models', 'seasonal_m')
    op.add_column('training_data_log', sa.Column('booking_value', sa.Float(), nullable=True))
    op.add_column('training_data_log', sa.Column('weather_indicator', sa.Float(), nullable=True))
    op.add_column('training_data_log', sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_training_data_log_record_date'), table_name='training_data_log')
    op.create_index(op.f('ix_training_data_log_record_date'), 'training_data_log', ['record_date'], unique=False)
    op.drop_column('training_data_log', 'booking_count')
    op.drop_column('training_data_log', 'last_refreshed_at')
    op.drop_column('training_data_log', 'typhoon_msw_max')
    op.drop_column('training_data_log', 'revenue_php')
    op.drop_column('training_data_log', 'is_mega_holiday')
    op.drop_column('training_data_log', 'is_long_weekend')
    op.drop_column('training_data_log', 'source_batch_ids')
    op.drop_column('training_data_log', 'holiday_intensity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_data_log', sa.Column('holiday_intensity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('training_data_log', sa.Column('source_batch_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('training_data_log', sa.Column('is_long_weekend', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('training_data_log', sa.Column('is_mega_holiday', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('training_data_log', sa.Column('revenue_php', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('training_data_log', sa.Column('typhoon_msw_max', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('training_data_log', sa.Column('last_refreshed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('training_data_log', sa.Column('booking_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_training_data_log_record_date'), table_name='training_data_log')
    op.create_index(op.f('ix_training_data_log_record_date'), 'training_data_log', ['record_date'], unique=True)
    op.drop_column('training_data_log', 'ingested_at')
    op.drop_column('training_data_log', 'weather_indicator')
    op.drop_column('training_data_log', 'booking_value')
    op.add_column('sarimax_models', sa.Column('seasonal_m', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sarimax_models', sa.Column('model_blob', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('sarimax_models', sa.Column('model_size_bytes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_sarimax_models_is_active'), 'sarimax_models', ['is_active'], unique=False)
    op.drop_column('sarimax_models', 'model_path')
    op.drop_constraint(None, 'model_diagnostics', type_='foreignkey')
    op.create_foreign_key(op.f('model_diagnostics_model_id_fkey'), 'model_diagnostics', 'sarimax_models', ['model_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_model_diagnostics_model_id'), 'model_diagnostics', ['model_id'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('forecast_week', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('predicted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('periods_ahead', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('predicted', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('lower_bound', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('upper_bound', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('exog_snapshot_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('actual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('absolute_error', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('squared_error', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('within_ci', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('scored_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['sarimax_models.id'], name=op.f('forecasts_model_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('forecasts_pkey')),
    sa.UniqueConstraint('model_id', 'forecast_week', 'periods_ahead', name=op.f('uq_model_forecast_week'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_forecasts_model_id'), 'forecasts', ['model_id'], unique=False)
    op.create_index(op.f('ix_forecasts_forecast_week'), 'forecasts', ['forecast_week'], unique=False)
    op.create_table('ingestion_batches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_size_bytes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_hash_sha256', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('row_count_raw', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('row_count_accepted', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('row_count_rejected', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_range_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('date_range_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ingestion_duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('ingestion_batches_pkey'))
    )
    op.create_index(op.f('ix_ingestion_batches_uploaded_at'), 'ingestion_batches', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_ingestion_batches_hash'), 'ingestion_batches', ['file_hash_sha256'], unique=False)
    op.create_index(op.f('ix_ingestion_batches_file_hash_sha256'), 'ingestion_batches', ['file_hash_sha256'], unique=True)
    op.create_table('dashboard_kpi_cache',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('valid_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('total_records', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_quality_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('revenue_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('growth_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('expected_bookings', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('peak_travel_period', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['sarimax_models.id'], name=op.f('dashboard_kpi_cache_model_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('dashboard_kpi_cache_pkey')),
    sa.UniqueConstraint('model_id', name=op.f('dashboard_kpi_cache_model_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('raw_bookings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('travel_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('order_reference', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('origin_destination', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('basic_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('taxes', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('booking_surcharge', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('vat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('net_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('raw_payload_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['ingestion_batches.id'], name=op.f('raw_bookings_batch_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('raw_bookings_pkey'))
    )
    op.create_index(op.f('ix_raw_bookings_travel_date'), 'raw_bookings', ['travel_date'], unique=False)
    op.create_index(op.f('ix_raw_bookings_origin_destination'), 'raw_bookings', ['origin_destination'], unique=False)
    op.create_index(op.f('ix_raw_bookings_order_reference'), 'raw_bookings', ['order_reference'], unique=False)
    op.create_index(op.f('ix_raw_bookings_generation_date'), 'raw_bookings', ['generation_date'], unique=False)
    op.create_index(op.f('ix_raw_bookings_batch_id'), 'raw_bookings', ['batch_id'], unique=False)
    op.create_table('training_jobs',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('requested_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('config_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('progress_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('current_step', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('resulting_model_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_traceback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['resulting_model_id'], ['sarimax_models.id'], name=op.f('training_jobs_resulting_model_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('training_jobs_pkey'))
    )
    op.create_index(op.f('ix_training_jobs_status'), 'training_jobs', ['status'], unique=False)
    op.drop_table('forecast_snapshots')
    op.drop_table('forecast_cache')
    # ### end Alembic commands ###
