"""add_actual_bookings_to_forecast_cache

Revision ID: aff2184fe97b
Revises: 72f0919c0006
Create Date: 2026-05-01 21:56:03.871482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aff2184fe97b'
down_revision: Union[str, Sequence[str], None] = '72f0919c0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecast_cache', sa.Column('actual_bookings', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecast_cache', 'actual_bookings')
    # ### end Alembic commands ###
