"""add confidence_tier sigma2 validation_graph_json

Revision ID: be8c1e78b5f9
Revises: 3274a8d87eb5
Create Date: 2026-05-02 00:37:59.956325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be8c1e78b5f9'
down_revision: Union[str, Sequence[str], None] = '3274a8d87eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset_snapshots', 'bookings_by_year_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('dataset_snapshots', 'bookings_by_month_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('dataset_snapshots', 'lead_time_distribution_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('dataset_snapshots', 'top_airlines_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('model_diagnostics', 'correlation_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.add_column('sarimax_models', sa.Column('sigma2', sa.Float(), nullable=True))
    op.drop_column('sarimax_models', 'peak_travel_period')
    op.drop_column('sarimax_models', 'total_records')
    op.drop_column('sarimax_models', 'data_quality_pct')
    op.drop_column('sarimax_models', 'expected_bookings')
    op.drop_column('sarimax_models', 'growth_rate')
    op.drop_column('sarimax_models', 'yearly_bookings_json')
    op.drop_column('sarimax_models', 'wmape')
    op.drop_column('sarimax_models', 'revenue_total')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sarimax_models', sa.Column('revenue_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sarimax_models', sa.Column('wmape', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sarimax_models', sa.Column('yearly_bookings_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('sarimax_models', sa.Column('growth_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sarimax_models', sa.Column('expected_bookings', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sarimax_models', sa.Column('data_quality_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sarimax_models', sa.Column('total_records', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sarimax_models', sa.Column('peak_travel_period', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('sarimax_models', 'sigma2')
    op.alter_column('model_diagnostics', 'correlation_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('dataset_snapshots', 'top_airlines_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('dataset_snapshots', 'lead_time_distribution_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('dataset_snapshots', 'bookings_by_month_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('dataset_snapshots', 'bookings_by_year_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
