"""add weekly_revenue to training_data_log

Revision ID: d2a7179525ad
Revises: 7e2b14097928
Create Date: 2026-04-27 01:09:34.521218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2a7179525ad'
down_revision: Union[str, Sequence[str], None] = '7e2b14097928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_data_log', sa.Column('weekly_revenue', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_data_log', 'weekly_revenue')
    # ### end Alembic commands ###
