"""add yearly bookings json column

Revision ID: d67243dfb197
Revises: 42ab9f105117
Create Date: 2026-04-26 22:27:36.339324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd67243dfb197'
down_revision: Union[str, Sequence[str], None] = '42ab9f105117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecast_snapshots', sa.Column('yearly_bookings_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecast_snapshots', 'yearly_bookings_json')
    # ### end Alembic commands ###
