"""catch_up_missing_columns

Revision ID: d8fb31cb8ab8
Revises: e2f3a4b5c6d7
Create Date: 2026-04-28 03:37:05.555885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'd8fb31cb8ab8'
down_revision: Union[str, Sequence[str], None] = 'e2f3a4b5c6d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecast_cache', sa.Column('risk_flag', sa.String(length=10), nullable=True))
    op.add_column('model_diagnostics', sa.Column('correlation_json', sa.JSON(), nullable=True))
    op.drop_column('sarimax_models', 'yearly_bookings_json')
    op.drop_column('sarimax_models', 'growth_rate')
    op.drop_column('sarimax_models', 'total_records')
    op.drop_column('sarimax_models', 'expected_bookings')
    op.drop_column('sarimax_models', 'peak_travel_period')
    op.drop_column('sarimax_models', 'data_quality_pct')
    op.drop_column('sarimax_models', 'revenue_total')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sarimax_models', sa.Column('revenue_total', sa.FLOAT(), nullable=True))
    op.add_column('sarimax_models', sa.Column('data_quality_pct', sa.FLOAT(), nullable=True))
    op.add_column('sarimax_models', sa.Column('peak_travel_period', sa.VARCHAR(length=100), nullable=True))
    op.add_column('sarimax_models', sa.Column('expected_bookings', sa.INTEGER(), nullable=True))
    op.add_column('sarimax_models', sa.Column('total_records', sa.INTEGER(), nullable=True))
    op.add_column('sarimax_models', sa.Column('growth_rate', sa.FLOAT(), nullable=True))
    op.add_column('sarimax_models', sa.Column('yearly_bookings_json', sqlite.JSON(), nullable=True))
    op.drop_column('model_diagnostics', 'correlation_json')
    op.drop_column('forecast_cache', 'risk_flag')
    # ### end Alembic commands ###
