"""sync orm to db

Revision ID: fba35f92f232
Revises: 8307f3ecb416
Create Date: 2026-05-02 00:44:27.797648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fba35f92f232'
down_revision: Union[str, Sequence[str], None] = '8307f3ecb416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sarimax_models', sa.Column('wmape', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sarimax_models', 'wmape')
    # ### end Alembic commands ###
