# api/dependencies/auth.py
"""
FastAPI dependencies for the access-control layer.

LAYERING:
  Layer 1 — get_db:               request-scoped session, always.
  Layer 2 — get_current_user:     resolves Bearer token → live User.
  Layer 3 — require_role(*roles): enforces RBAC.
  Layer 3.b — convenience aliases require_admin / require_analyst /
             require_any cover the three use-case shapes in the blueprint.

The dependency form is preferred over middleware because:
  - Self-documenting: `Depends(require_admin)` is visible in the function
    signature AND in the OpenAPI schema generated by FastAPI.
  - Compositional: Layer 3 explicitly depends on Layer 2 so the user is
    resolved exactly once per request, even if multiple guards run.
  - Testable: app.dependency_overrides[require_admin] = lambda: fake_admin
    in pytest, no JWT minting required.

ISO 25010 → Maintainability → Modifiability and Testability.
ISO 25010 → Security → Access Control (least privilege at the asset).
"""

from __future__ import annotations

import logging
from typing import Annotated, Iterable

from fastapi import Depends, HTTPException, Request, status
from fastapi.security import OAuth2PasswordBearer
from jose import JWTError
from sqlalchemy.orm import Session

from core.security import TOKEN_TYPE_ACCESS, decode_token
from domain.auth_models import User, UserRole
from repository import auth_repository as auth_repo
from repository.model_repository import SessionLocal

logger = logging.getLogger(__name__)

# tokenUrl points at the LOGIN endpoint (Phase 2.6) — Swagger uses this
# to wire its "Authorize" button. The path MUST match the prefix we
# include the auth router under in api/main.py.
oauth2_scheme = OAuth2PasswordBearer(tokenUrl="/auth/login", auto_error=False)


# ═════════════════════════════════════════════════════════════════════════════
# LAYER 1 — request-scoped DB session
# ═════════════════════════════════════════════════════════════════════════════


def get_db():
    """
    Yield a SQLAlchemy Session that is closed after the request finishes.

    Note: api/main.py defines its own get_db inline today. That one stays
    in place so existing endpoints don't need to change in this phase.
    Phase 5 will retrofit the existing endpoints to import THIS one and
    delete the duplicate. Both functions are identical — no behavioural
    drift in the meantime.
    """
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


DbDep = Annotated[Session, Depends(get_db)]


# ═════════════════════════════════════════════════════════════════════════════
# LAYER 2 — resolve Bearer → User
# ═════════════════════════════════════════════════════════════════════════════


def _client_ip(request: Request) -> str | None:
    """
    Best-effort client IP. Behind Cloud Run's proxy, the originating
    address is in X-Forwarded-For (Cloud Run sets it). Falls back to
    the raw socket peer for local dev.
    """
    fwd = request.headers.get("x-forwarded-for")
    if fwd:
        # X-Forwarded-For may be a comma-separated chain. The leftmost
        # entry is the original client.
        return fwd.split(",")[0].strip() or None
    return request.client.host if request.client else None


def _credentials_exception() -> HTTPException:
    """
    Generic 401. The detail is a STRING (not a dict) so it flows through
    the existing `_extract_http_error_payload` helper in api/main.py and
    produces the standard {"error": {"code", "message", "details"}}
    envelope. Same shape as every other handled error in the system.
    """
    return HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Could not validate credentials.",
        headers={"WWW-Authenticate": "Bearer"},
    )


def get_current_user(
    request: Request,
    token: Annotated[str | None, Depends(oauth2_scheme)],
    db: DbDep,
) -> User:
    """
    Resolve the Bearer token to a live, active User row.

    Failure modes (all → 401, identical message):
      - No Authorization header.
      - Header is malformed / wrong scheme.
      - JWT signature invalid.
      - JWT expired.
      - JWT typ != "access" (refresh-token-as-access misuse).
      - User UUID in `sub` doesn't match any row.
      - User row exists but is_active=False.

    Why all paths return the SAME 401:
      Distinguishing "expired" from "deactivated" leaks state to attackers.
      The frontend has its own logic ("on 401 from a non-/auth endpoint,
      try refresh; if /auth/refresh also 401s, hard-logout"). It doesn't
      need server-side hints.

    `auto_error=False` on oauth2_scheme means FastAPI doesn't raise on a
    missing header — we get None and raise our own consistent 401.
    """
    if not token:
        raise _credentials_exception()

    try:
        payload = decode_token(token, expected_type=TOKEN_TYPE_ACCESS)
    except JWTError:
        raise _credentials_exception()

    user_id = payload.get("sub")
    if not user_id:
        raise _credentials_exception()

    user = auth_repo.fetch_user_by_id(db, user_id)
    if user is None or not user.is_active:
        raise _credentials_exception()

    # Stash the resolved client IP on request.state so the router can
    # forward it into audit calls without re-parsing headers. This is the
    # FastAPI idiom for request-scoped derived data.
    request.state.client_ip = _client_ip(request)
    request.state.user_agent = request.headers.get("user-agent")

    return user


CurrentUserDep = Annotated[User, Depends(get_current_user)]


# ═════════════════════════════════════════════════════════════════════════════
# LAYER 3 — RBAC enforcement
# ═════════════════════════════════════════════════════════════════════════════


def require_role(*allowed: UserRole):
    """
    Factory that returns a Depends-able callable enforcing role membership.

    Usage:
        @router.get("/admin/users", dependencies=[Depends(require_admin)])
        ...
        # OR, if the endpoint needs the user object:
        def handler(user: CurrentUserDep = Depends(require_admin)): ...

    The 403 response includes the role required so a frontend showing
    a "you can't do this" message can be specific. We return THE ROLE
    NEEDED, not the roles the user lacks — minimal info disclosure.
    """
    if not allowed:
        raise ValueError("require_role() requires at least one allowed role.")

    allowed_set = frozenset(allowed)

    def _checker(user: CurrentUserDep) -> User:
        if user.role not in allowed_set:
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="Insufficient permissions for this operation.",
            )
        return user

    # Name the inner function for nicer Swagger docs.
    _checker.__name__ = f"require_role({','.join(r.value for r in allowed)})"
    return _checker


# Convenience aliases — exact mappings to the blueprint §5.7 table.
require_admin = require_role(UserRole.ADMIN)
require_analyst = require_role(UserRole.ADMIN, UserRole.ANALYST)
require_any = require_role(UserRole.ADMIN, UserRole.ANALYST, UserRole.VIEWER)